user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {
    upstream gcsproxy {
        server '127.0.0.1:8989';
    }

    server {
	    listen 8080 http2;
	    #listen [::]:80;
	    #listen 443 http2;
        server_name _;

        # Logs
    	#access_log off;
        error_log /var/log/nginx/gcsproxy.error.log error;

    	include mime.types;

    	# Disable actions like POST that have no business on GCS buckets.
        if ($request_method !~ "GET|HEAD|PURGE|OPTIONS") {
            return 405;
        }

	location /download/ {
            # Large files should be passed directly to the client, without buffering
	    proxy_buffering off;

	    # CORS settings.  As of 2026-01-07, even GCS has a `*` in the allowlist.
	    # Adapted from wide-open config at https://enable-cors.org/server_nginx.html
	    if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, HEAD, OPTIONS';
	    }
	    if ($request_method = 'GET') {
                add_header "Access-Control-Allow-Origin" "*" always;
		#add_header 'access-control-expose-headers' 'content-length,content-range' always;
		add_header "access-control-expose-headers" "*" always;
	    }
	    if ($request_method = 'HEAD') {
                add_header "Access-Control-Allow-Origin" "*" always;
		#add_header 'access-control-expose-headers' 'content-length,content-range' always;
                add_header "access-control-expose-headers" "*" always;
	    }

	    # NatCap Data Cache rules
	    #
	    # We are specifically granting public access to specific subdirectories here.
	    # This is a little tedious, but it also means that we have to explicitly grant access to specific subdirs.
            rewrite ^/downloads/global/(.*)$ /natcap-data-cache/global/$1 break;
            rewrite ^/downloads/collaborator-data/(.*)$ /natcap-data-cache/collaborator-data/$1 break;
            rewrite ^/downloads/natcap-projects/(.*)$ /natcap-data-cache/natcap-projects/$1 break;

	    # NatCap Clipping Service Rules
            rewrite ^/downloads/clipped/(.*)$ /jupyter-app-temp-storage/clipped/$1 break;
            proxy_pass http://gcsproxy$uri;
        }

	#return 404;

	# Commenting this out, otherwise one could formulate a URL to grant access to anything!
	#
	#location / {
        #    proxy_pass http://gcsproxy$uri;
        #}
    }
}
